### ISSUE TITLE
Large datasets handing

### ISSUE THREAD

**Issue by PBrockmann** [john-guerra/navio#37]
What are the limitations of navio concerning the number of records ?

I have a file with 25 millions of records I would like to use ? 
A test with a 10 millions records file shows me that navio is still usable with some slowdown however.

What could be the strategy to manage those large files ?

**Comment by john-guerra** [comment]
From my experiments it can handle whatever data you can get into the browser. As an example check this observable https://observablehq.com/@john-guerra/socrata-load-multiples-pages that loads 3.3M records. If you wait for it to load the data and then hit Visualize it, it will show a navio that will load after 40 - 70s depending on the browser. Sorting will be slow, but filtering is pretty smooth.

In other experiments loading local files I have been able to work with files over 200MB. There are ways of optimizing, for example specifying the attributes with their own types instead of using the *addAllAttribs* method that tries to infer them

**Comment by john-guerra** [comment]
Revisited as part of a 2026-08-01 whole-repo review. Re-read the rendering architecture (canvas marks, pixel-bounded representative sampling in `computeRepresentatives`, brush-drag vs brush-end correctly separated) and it's already sound for large datasets — not an inherent SVG/DOM ceiling. The actual drag turned out to be unconditional `DEBUG=true` console-logging on every mousemove (#58) and a scale object rebuilt on every pointer event in the tooltip/hover path (#62), plus some uncached O(n) hot paths (#61). Filed as separate, concrete issues — see `docs/ai/2026-08-01-repo-review-and-roadmap.md`, §8 for the full analysis.
